/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GroupItem.java
 *
 * Created on 2010-maj-26, 21:14:48
 */

package melonjuice;

/**
 *
 * @author DmZ
 */
public class GroupItem extends javax.swing.JPanel {

    /** Creates new form GroupItem */
    public GroupItem() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(melonjuice.MelonJuiceApp.class).getContext().getResourceMap(GroupItem.class);
        jLabel1.setText(resourceMap.getString("jLabelgroupName.text")); // NOI18N
        jLabel1.setName("jLabelgroupName"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabelMemberAmount.text")); // NOI18N
        jLabel2.setName("jLabelMemberAmount"); // NOI18N

        jButton1.setLabel(resourceMap.getString("jButtonGo.label")); // NOI18N
        jButton1.setName("jButtonGo"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabelPing.text")); // NOI18N
        jLabel3.setName("jLabelPing"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabelStatus.text")); // NOI18N
        jLabel4.setName("jLabelStatus"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

}
